resources:
- ../../../../../components/certificates/base

patches:
  - patch: |-
      - op: replace
        path: /spec/servingCerts/namedCertificates/0/names/0
        value: api.lab.etbit.io
    target:
      group: config.openshift.io
      kind: APIServer
      name: cluster
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - api.lab.etbit.io
    target:
      kind: Certificate
      name: openshift-api
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - '*.apps.lab.etbit.io'
      - op: replace
        path: /spec/commonName
        value: '*.apps.lab.etbit.io'
    target:
      kind: Certificate
      name: openshift-wildcard
