apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

resources:
  - subscription.yaml
  - lvmcluster.yaml
  - namespace.yaml
  - operatorgroup.yaml
  - storageclass.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/storage/deviceClasses/0/deviceSelector
        value:
          paths:
            - /dev/sda
    target:
      kind: LVMCluster