resources:
- ../../../../../components/lvm-operator/base
- storageclass.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/storage/deviceClasses/0/deviceSelector
        value:
          paths:
            - /dev/sda
    target:
      kind: LVMCluster
