apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../components/lvm-operator/base

patches:
  - patch: |-
      - op: add
        path: /spec/storage/deviceClasses/0/deviceSelector
        value:
          paths:
            - /dev/nvme1n1
    target:
      kind: LVMCluster
