apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - set-max-pods.yaml
  - ../../../../../components/wake-on-lan/base

patches:
  - patch: |
      - op: replace
        path: /spec/config/systemd/units/0/name
        value: wol@enp8s0.service
      - op: add
        path: /metadata/labels/machineconfiguration.openshift.io~1role
        value: master
    target:
      kind: MachineConfig
      name: 99-wol-service
