resources:
- ../../../../../components/adguard-home

patches:
- patch: |-
    - op: replace
      path: /spec/storageClassName
      value: "lvms-vg1"
  target:
    kind: PersistentVolumeClaim
    name: adguard-pvc