apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: kyverno
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: policies
      operator: In
      values:
      - kyverno
