apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: sensor-tls
  namespace: stackrox-secured-cluster-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: sensor-tls
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: ACS_SENSOR_TLS
