apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: sensor-tls
  namespace: stackrox-secured-cluster-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: sensor-tls
    creationPolicy: Owner
  dataFrom:
  - extract:
      # To get this key, use JSON
      # Format: echo '{}' | jq --arg cert "$(<sensor-tls.crt)" '{"NAME OF KEY": $cert}')
      # Example: echo '{}' | jq --arg cert "$(<sensor-tls.crt)" '{"ca.pem": $cert}'
      # If more than one cert (likely for ACS), use all in a single JSON secret, comma separated
      #
      # Result:
      # {
      #   "admission-control-cert.pem": "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----",
      #   "admission-control-key.pem": "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----",
      #   "ca.pem": "-----BEGIN EC PRIVATE KEY-----\n...\n-----END EC PRIVATE KEY-----"
      # }
      key: ACS_SENSOR_TLS
