apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: admission-control-tls
  namespace: stackrox-secured-cluster-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: admission-control-tls
    creationPolicy: Owner
  dataFrom:
  - extract:
      # To get this key, use JSON
      # Format: echo '{}' | jq --arg cert "$(<admission-control-tls.crt)" '{"NAME OF KEY": $cert}')
      # Example: echo '{}' | jq --arg cert "$(<admission-tls.crt)" '{"ca.pem": $cert}'
      # If more than one cert (likely for ACS), use all in a single JSON secret, comma separated
      key: ACS_ADMISSION_CONTROL_TLS
