apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-logging

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/size
      value: 1x.extra-small
  target:
    kind: LokiStack
    name: logging-loki
- path: ingestion-rate-patch.yaml
  target:
    kind: LokiStack
    name: logging-loki
