apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- oidc-client-secret.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/identityProviders/-
        value:
          name: LabSSO
          mappingMethod: claim
          type: OpenID
          openID:
            clientID: openshift
            clientSecret:
              name: oidc-client-secret
            extraScopes:
            - email
            - profile
            extraAuthorizeParameters:
              include_granted_scopes: "true"
            claims:
              preferredUsername:
              - preferred_username
              - email
              name:
              - nickname
              - given_name
              - name
              email:
              - custom_email_claim
              - email
            issuer: https://sso.ocplab.com/realms/ocplab
    target:
      group: config.openshift.io
      kind: OAuth
      name: cluster
      version: v1
