EXTERNAL_TLS_TERMINATION: false
SERVER_HOSTNAME: registry.apps.home.ocplab.com
PREFERRED_URL_SCHEME: https
DISTRIBUTED_STORAGE_CONFIG:
  # using Minio on QNAP NAS
  radosGWStorage:
    - RadosGWStorage
    - access_key: XXXXX
      secret_key: XXXX
      bucket_name: quay
      hostname: lab-nas.ocplab.com
      is_secure: true
      port: 9000
      storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
  - radosGWStorage
SSO_LOGIN_CONFIG:
  CLIENT_ID: quay
  CLIENT_SECRET: 723782ba-95d4-4d95-8b04-efebce0adf86
  OIDC_SERVER: https://sso-sso.apps.home.ocplab.com/auth/realms/openshift/
  LOGIN_SCOPES:
    - openid
  SERVICE_NAME: OpenShift
SUPER_USERS:
  - admin
  - quayadmin
FEATURE_DIRECT_LOGIN: true
FEATURE_USER_INITIALIZE: true
FEATURE_QUOTA_MANAGEMENT: true
FEATURE_PROXY_CACHE: true
