resources:
- ../../../../../components/registry-sno-base

patches:
  - patch: |-
      - op: replace
        path: /spec/storageClassName
        value: lso-vg1
    target:
      kind: PersistentVolumeClaim
      name: image-registry
