resources:
- ../../../../../components/registry-sno-base/base

patches:
  - patch: |-
      - op: replace
        path: /spec/storageClassName
        value: openshift-storage.noobaa.io
    target:
      kind: PersistentVolumeClaim
      name: image-registry
      namespace: openshift-image-registry
