apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-static-ghost
  namespace: ghost
  labels:
    app: ghost
spec:
  storageClassName: lvms-vg1 # Change this to your storageClassName
  accessModes:
  - ReadWriteOnce # Change this to your accessModes
  resources:
    requests:
      storage: 5Gi
