# Assumes the cluster admin had pre-created the sealed-secrets project and secret.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-compliance

resources:
- github.com/redhat-cop/gitops-catalog/compliance-operator/operator/overlays/release-0.1
- ocp-cis-tailored-profile.yaml
- ocp-cis-node-tailored-profile.yaml
- cis-compliance-scan-setting-binding.yaml
- cis-compliance-scansetting.yaml

patches:
- patch: |-
    - op: add
      path: /metadata/labels
      value: {"openshift.io/cluster-monitoring": "true"}
  target:
    kind: Namespace
- patch: |-
    - op: replace
      path: /spec/channel
      value: stable
  target:
    kind: Subscription
    name: compliance-operator
