apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: ocp4-cis-node-lab
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  extends: ocp4-cis-node
  description: Lab CIS node profile
  title: Lab CIS node profile
  disableRules:
  - name: ocp4-file-permissions-etcd-data-dir
    rationale: Default value of `drwxr-xr-x.` is fine
  - name: ocp4-kubelet-enable-protect-kernel-defaults
    rationale: Not applicable
  - name: ocp4-kubelet-enable-protect-kernel-sysctl
    rationale: Not applicable
