kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: adguard-scc-admin
  namespace: adguard
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:adguard:default