apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: adguard-rolebinding
  namespace: adguard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: adguard-scc-clusterrole 
subjects:
- kind: ServiceAccount
  name: default
  namespace: adguard