apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-pv-conf
  namespace: adguard
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: REPLACE
  hostPath:
    path: "/mnt/data/adguard"