apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adguard-scc-clusterrole 
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nonroot
  resources:
  - securitycontextconstraints
  verbs:
  - use