apiVersion: v1
kind: ServiceAccount
metadata:
  name: postsync-create-roxsecrets
  namespace: stackrox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: postsync-create-roxsecrets
  namespace: stackrox
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: postsync-create-roxsecrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: postsync-create-roxsecrets
subjects:
  - kind: ServiceAccount
    name: postsync-create-roxsecrets
    namespace: stackrox
