resources:
- ../../../../../components/banner/base

patches:
- patch: |-
    - op: replace
      path: /spec/backgroundColor
      value: "#0066CC"
  target:
    kind: ConsoleNotification
    name: banner
