apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: autodetect-local
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - lab
              - lab-worker
  storageClassName: lso-vg1
  volumeMode: Filesystem
  fsType: xfs
  deviceInclusionSpec:
    deviceTypes:
      - /dev/sda
    minSize: 100G
