apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  outputs:
    - name: loki-app
      type: loki
      url: http://lokistack-gateway-http.openshift-logging.svc:8080/api/logs/v1/application
      secret:
        name: lokistack-gateway-bearer-token
    - name: loki-infra
      type: loki
      url: http://lokistack-gateway-http.openshift-logging.svc:8080/api/logs/v1/infrastructure
      secret:
        name: lokistack-gateway-bearer-token
    - name: loki-audit
      type: loki
      url: http://lokistack-gateway-http.openshift-logging.svc:8080/api/logs/v1/audit
      secret:
        name: lokistack-gateway-bearer-token
  pipelines:
    - name: send-app-logs
      inputRefs:
        - application
      outputRefs:
        - loki-app
    - name: send-infra-logs
      inputRefs:
        - infrastructure
      outputRefs:
        - loki-infra
    - name: send-audit-logs
      inputRefs:
        - audit
      outputRefs:
        - loki-audit
