apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  size: 1x.extra-small
  storage:
    schemas:
      - effectiveDate: '2022-06-01'
        version: v12
    secret:
      name: loki-storage
      type: s3
  storageClassName: lvms-vg1
  tenants:
    mode: openshift-logging
