apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/redhatryan
  services.yaml: |
    - My First Group:
        - My First Service:
            href: https://console-openshift-console.apps.lab.etbit.io/multicloud/infrastructure/clusters/managed
            description: Red Hat Advanced Cluster Management

    - My Second Group:
        - My Second Service:
            href: https://central-stackrox.apps.lab.etbit.io/
            description: Red Hat Advanced Cluster Security

    - My Third Group:
        - My Third Service:
            href: https://openshift-gitops-server-openshift-gitops.apps.lab.etbit.io/
            description: OpenShift GitOps
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
