apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: homepage
  namespace: default
spec:
  host: homepage.apps.lab.etbit.io
  tls:
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIE8zCCA9ugAwIBAgISBHwEhi9AtbSWSwaO8GHeaBjIMA0GCSqGSIb3DQEBCwUA
      MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
      EwJSMzAeFw0yMzExMTMwMzI0MTBaFw0yNDAyMTEwMzI0MDlaMB4xHDAaBgNVBAMM
      EyouYXBwcy5sYWIuZXRiaXQuaW8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQCwuWFGak0e0k8xSBU8a7mKlQzihITmxjOZX8m2IiOPQ8l0ek+Iy30uncwK
      55FTdUckKDafH6xQ2ZYjFm6KgfKQKfRT4bv2Fft/e4G8ft7cwXfNYeLGD64hJEgr
      E4ZExyRIuy6ukXFlZP0+mJMI8o5bw+pBp96Z0od28L0Hfj3l6Vr3RNQQckC951X4
      G6T3tSo8G9WCtP5aEDb6sjr7OnCXFtU2yF8pKPfJ70FCEv3rlvXMZitovw309hhy
      7juns0ZpEfRVjnpj6ZlYAAxAeXEfE75rtYkerSg2NPvYAemc/hZu2PsavuvleHib
      UEHD6b6tTkPSVVXGc9qwor69fwOPAgMBAAGjggIVMIICETAOBgNVHQ8BAf8EBAMC
      BaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAw
      HQYDVR0OBBYEFKyyaosZ1qEYnwlU/tstE8w7f7XBMB8GA1UdIwQYMBaAFBQusxe3
      WFbLrlAJQOYfr52LFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0
      cDovL3IzLm8ubGVuY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMuaS5sZW5j
      ci5vcmcvMB4GA1UdEQQXMBWCEyouYXBwcy5sYWIuZXRiaXQuaW8wEwYDVR0gBAww
      CjAIBgZngQwBAgEwggEEBgorBgEEAdZ5AgQCBIH1BIHyAPAAdwBIsONr2qZHNA/l
      agL6nTDrHFIBy1bdLIHZu7+rOdiEcwAAAYvG7DZ2AAAEAwBIMEYCIQCO/qwkAQT+
      tnStsBnhL+Z6k49zkzdWyBclisRwT5QIGwIhAP2lgNSPKm/3ER0eE06mtw3DrHB7
      ++els/2YM+ck8VzIAHUAO1N3dT4tuYBOizBbBv5AO2fYT8P0x70ADS1yb+H61BcA
      AAGLxuw2iAAABAMARjBEAiA6B7da3Lyl+WSLwTxjxyfjnLElmPfmDTKMrj23Gfph
      NwIgAjc/p6gGbY8jdSEPgTSYFTvjAkUCL0i+NsDW2IRoeBYwDQYJKoZIhvcNAQEL
      BQADggEBAFa9LYl3Vk58LVwZC1FcH5ixrDD0DmsGYr08EqL75y6FlaHcs2z85DSY
      r4z/w2B5ArZI2PEbdUghDbcK71xLzYdFFMvnHmk4aVVeKOKd2daxDrxYpU7aufJp
      Xh/TQjaFYCoDtLAqpZrXSO0wOaPAlK4AZJQqa6lT5ILmB724QTCLmyj6Et/Dl8U4
      /2oRyraUyiPRtylVNn7jECmhJZL2yCCW0zi2WfTMY1aJUOz8WP2Xnt4qD5QNhZG2
      LIBy3tsAC7nksVMIvCDZb9R2rKgrvowWZm70SFHQcqGAkLphKBS4f0v+Wm4nsy1C
      LhKlYEBX4ih6uJIyTU57/O87wnfiW3s=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
      TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
      cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
      WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
      RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
      R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
      sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
      NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
      Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
      /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
      AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
      Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
      FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
      AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
      Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
      gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
      PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
      ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
      CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
      lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
      avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
      yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
      yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
      hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
      HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
      MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
      nLRbwHOoq7hHwg==
      -----END CERTIFICATE-----
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEAsLlhRmpNHtJPMUgVPGu5ipUM4oSE5sYzmV/JtiIjj0PJdHpP
      iMt9Lp3MCueRU3VHJCg2nx+sUNmWIxZuioHykCn0U+G79hX7f3uBvH7e3MF3zWHi
      xg+uISRIKxOGRMckSLsurpFxZWT9PpiTCPKOW8PqQafemdKHdvC9B3495ela90TU
      EHJAvedV+Buk97UqPBvVgrT+WhA2+rI6+zpwlxbVNshfKSj3ye9BQhL965b1zGYr
      aL8N9PYYcu47p7NGaRH0VY56Y+mZWAAMQHlxHxO+a7WJHq0oNjT72AHpnP4Wbtj7
      Gr7r5Xh4m1BBw+m+rU5D0lVVxnPasKK+vX8DjwIDAQABAoIBABvfINhaK4+Q26yK
      Ec9Vrg2NNFsFS3CaEck+sjFncPRHXJ5iK+kHLtcLTALsQp9G/9FUBklSVXrq1iLy
      hryRgg/6je4sy9gj32ZbtDpmR//JA3wA1CMole3kKv2gNqziO3a9Dr+5cIjtRIN6
      zLW8i3ctjuSL9S+NZI/9p9Jmtpxrzeo5qYPaNrMMGXPp+A8+2UMoxu5RBam3h5d5
      R1/lrCBOTPNKdZZc8QIu2FtueDwSJNcvPmeTiEJvptTFNzbg96uk6PISVDxV7rkK
      6nE5r7oEACO0+AdWhHoUtPeqhEfKMpSlDFE3rGkRsNRyVWPGm221dlEMV2peW57W
      13knNAECgYEAwbVvg2QoN0777gnQu3wXTGIdnIZQWzHkE6Lml88B+vtQrQ8Bfdn3
      fJKxT/Wvr/LL4kPR3bA/JK9ksi+z6riYdM6kYXW1ryKUiGk9wyJxFYNsfKdRUrRY
      qFDiH8CaFRk7NY5AyUwFC5w/ly3KcYewnk5UCaQ4vE/PcOpOL4uuf58CgYEA6Y27
      dsck68eeN5VwqKkEsKAVv/F/FwCdC/yg3f3tqPo6VhXCsocBvpsb/09jnCzYhwSD
      6uB5+JQ7kol31vmaD+dkWHKW2r5Oc6IJh9NtyH6h2orNut2vWjvh8S8yCSnXn+pQ
      DAFaCLBNo3ST1gc4WoSaOgTVDv5syPPXksLjNhECgYBDxARZ89z51GDgGoDyRewk
      paJ0Uqyj6qU+lVuUOjAYLHlBwaEk9O7Wnr73GR04MXlQE6fEpVbBr7ZLe9K2R5PW
      MUBic/p2ZWOPATpBHLhw7UQzq5kQlNT7NSiWMRv2S5hiGPzjLvwI3sWETtmms/B+
      wSo3IUNT5ZvNhbqKeZQ3QwKBgQDL236p6qF7fD3J3pL7ZKxHTzQs2ipIdaye7d+s
      ZRywxdltkojjM5x+Nv11GGKlyy8kivhqZ42PQDPPcFY+OpgTEbIw0bSDMmFf5SvU
      duP4gS/dhhKU7TNF28cXsk5GWVNwriE4mWVw+BKMfhEcXCkAOYY05kriT4m8zbp4
      y8tvQQKBgQCVwPCDwqCRlhHrq5a6cdKrpMhjgo42+H6PGECfQ5heNTvdFC545pEZ
      90qBvdMyMqcGvXLLUOKh31+Q5VJL9R99uji2ULMekHXjNOCuND0uYLLOa37PrSKr
      j/+OD/uIOXxbU45DrJaczNAg9u/GvKKw8dh9ufS1BlFKEeg7AahyEA==
      -----END RSA PRIVATE KEY-----
    termination: edge
  to:
    kind: Service
    name: homepage
    weight: 100
  wildcardPolicy: None