apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Etbit Homelab
    background: https://images.unsplash.com/photo-1682687220211-c471118c9e92?q=80&w=3270&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
    headerStyle: clean
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Github:
        - RedHatRyan:
            - abbr: GH
              href: https://github.com/redhatryan
  services.yaml: |
    - RHACM:
        - RHACM Dashboard:
            href: https://console-openshift-console.apps.lab.etbit.io/multicloud/infrastructure/clusters/managed
            description: Red Hat Advanced Cluster Management

    - RHACS:
        - RHACS Dashboard:
            href: https://central-stackrox.apps.lab.etbit.io/
            description: Red Hat Advanced Cluster Security

    - OpenShift GitOps:
        - ArgoCD Dashboard:
            href: https://openshift-gitops-server-openshift-gitops.apps.lab.etbit.io/
            description: OpenShift GitOps
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
