apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
- cert-manager-ns.yaml
- letsencrypt-external-cf.yaml
- cf_letsencrypt-staging-cluster-issuer.yaml
- cf_letsencrypt-prod-cluster-issuer.yaml