apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
- cert-manager-ns.yaml
- letsencrypt-external.yaml
- letsencrypt-staging-cluster-issuer.yaml
- letsencrypt-prod-cluster-issuer.yaml
- acme-ingress-ns.yaml
- acme-ingress-prod.yaml
- acme-ingress-staging.yaml