apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Use the Let's Encrypt staging environment for testing
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ryan@etbitconsulting.com
    privateKeySecretRef:
      name: retten-redhat-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: ryan@etbitconsulting.com
          apiKeySecretRef:
            name: cloudflare-api-key
            key: api-key

