apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Use the Let's Encrypt staging environment for testing
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ryan@etbitconsulting.com
    # This key doesn't exist, cert-manager creates it
    privateKeySecretRef:
      name: retten-redhat-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: openshift-default  
#    - selector:
#        dnsZones:
#          - "etbit.io"
#      dns01:
#       cloudflare:
#          email: ryan@etbitconsulting.com
#          apiKeySecretRef:
#            name: cloudflare-api-key
#            key: secret-access-key

