apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: cloudflare-api-key
  data:
    - apiKey: secret-access-key
      remoteRef:
        key: LETSENCRYPT
