apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: letsencrypt
  data:
    - api-key: cloudflare-api-key
      remoteRef:
        key: LETSENCRYPT
