apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: ghost
  repo: oci://registry-1.docker.io/bitnamicharts/ghost
  version: "5.74.3"
  namespace: ghost
  valuesFile: values.yaml