apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: ghost
  repo: https://github.com/bitnami/charts/bitnami/ghost
  version: "5.74.3"
  namespace: ghost
  valuesFile: values.yaml