resources:
- ../../../../../components/lvm-operator/base

patches:
  - patch: |-
      - op: add
        path: /spec/storage/deviceClasses/0/deviceSelector
        value:
          paths:
            - /dev/nvme0n1
    target:
      kind: LVMCluster
