apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ../../../login-template/base

patches:
  - patch: |-
      - op: add
        path: /spec/templates
        value:
          login:
            name: matrix-login-template
          providerSelection:
            name: matrix-providers-template
    target:
      group: config.openshift.io
      kind: OAuth
      name: cluster
      version: v1
