apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Validate=false,ServerSideApply=true
spec:
  defaultCertificate:
    name: openshift-wildcard-certificate
