apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openshift-wildcard
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  secretName: openshift-wildcard-certificate
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: '*.apps.replace.me'
  dnsNames:
  - '*.apps.replace.me'
