apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openshift-api
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  secretName: openshift-api-certificate
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - replace.me
