apiVersion: v1
kind: Pod
metadata:
  name: ubi8
  labels:
    app: ubi8
  namespace: validated-pattern
spec:
  containers:
    - name: ubi8
      image: 'registry.access.redhat.com/ubi8/ubi'
      stdin: true
      tty: true